spring:
  application:
    name: CICDDemoApplication

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true

  #docker run -p 8085:8085 --name cicdapp rchapagain/cicdapp:dev
  #docker pull rchapagain/cicdapp:dev